### ISSUE TITLE
App crashed when deleting recorded audio file from App

### ISSUE THREAD

**Issue by PG90** [ramt57/CallRecorder#1]
App crashes every time whenever we deletes a recorded call audio file.

**Comment by ramt57** [comment]
I just fixed the error.kindly update your project

**Comment by PG90** [comment]
It's working now, thanks

**Comment by ramt57** [comment]
i added some new thing plz update your project.fixed some bugs too

**Comment by PG90** [comment]
In this the days are counted from the time of call recorded, I mean calls will be moved to yesterday when it completes 24 hours. Not counting on the actual clock timings. Hope you understand what I mean.

**Comment by ramt57** [comment]
Sorry i do not understand.
